[workspace]
members = [
    "discord_bot",
    "game_manager", "game_manager",
]
resolver = "2"

[profile.android-dev]
inherits = "dev"

[profile.server-dev]
inherits = "dev"

[profile.wasm-dev]
opt-level = 1
inherits = "dev"
